#!/bin/sh

run() {
	set -e
	pcrt=$(readlink -f ./apache/crts)
	if [ ! -e tests/newrepos/gitolite-admin ]; then
		git -c http.https://localhost:6443/.sslCAInfo=${dirp0}/apache/crts -c credential.helper=passwd clone https://gitoliteadm@localhost:6443/hgit/gitolite-admin tests/newrepos/gitolite-admin
	fi
	. tests/utils
	cd tests/newrepos/gitolite-admin
	git_config 6443 "${pcrt}" gitoliteadm
}
