#!/bin/sh

run() {
	set -e
	if [ ! -e tests/newrepos/gitolite-admin-ext ]; then
		echo "no gitolite-admin-ext repo found">> tests/err
		return 1
	fi
	. tests/utils
	pcrt=$(readlink -f ./apache/crts)
	cd tests/newrepos/gitolite-admin-ext
	pwd
	git_config 6443 "${pcrt}" gitoliteadm
	if [ ! -e .git/refs/heads/master_ext ]; then
		echo "no master_ext branch found">> tests/err
		return 1
	fi
	git checkout master_ext
	gconf="conf/gitolite.conf"
	git reset ${gconf}

	if [ ${reset} -eq 0 ]; then
		echo "resetting to 'Add projextrdr to @all in master_ext'"
		check=$(git log --format=format:%H --grep "Add projextrdr to @all in master_ext$" master)
		if [ "check" = "" ]; then
			echo "Impossible to reset: 'Add projextrdr to @all in master_ext$' not found" >> ${dirp0}/tests/err
			return -1
		fi
		git reset --hard ${check}
	fi
	# git checkout ${gconf}

	append_multiple_before 'repo\s+module2' '@projectext2\s+=\s+module2$' \
	"${gconf}" 4 '^subconf\s.*$' "
repo module2
    RW+   = projextadm2

@projectext2 = module2
"

	append_multiple_after 'RW\s+=\s+projextadm2$' '-\s+VREF\/NAME\/\s+=\s+projextadm2$' "${gconf}" 3 'RW+\s\+=\s\+gitoliteadm$' \
"\\
	RW                                     = projextadm2\\
	RW VREF/NAME/conf/subs/projectext2     = projextadm2\\
	-  VREF/NAME/                          = projextadm2"

    mkdir -p conf/subs
	echo "repo @projectext2
	RW+   = projextadm2" > conf/subs/projectext2.conf
	git add conf/subs/projectext2.conf

	if [ ${append} -eq 0 ]; then
		git_status_diff_add_commit_log "${gconf}" "Add new repo module2 to projectext2 group"
	fi

	check_if_pushed "origin" "[Aa]dd new repo module2 to projectext2 group$" "master_ext"
	if [ "${check}" = "" ]; then
		echo "no commit 'Add new repo module2 to projectext2 group'">> ${dirp0}/tests/err
		return 1
	fi
}
