#!/bin/sh

run() {
	set -e
	. tests/utils
	pcrt=$(readlink -f ./apache/crts)
	cd tests/newrepos/gitolite-admin
	pwd
	git_config 6443 "${pcrt}" "projextrdr"
	git checkout master
	gconf="conf/gitolite.conf"

	if [ ${reset} -eq 0 ]; then
		echo "resetting to 'Add projextrdr to @all in master'"
		check=$(git log --format=format:%H --grep "Add projextrdr to @all in master$" master)
		if [ "check" = "" ]; then
			echo "Impossible to reset: 'Add projextrdr to @all in master$' not found" >> ${dirp0}/tests/err
			return -1
		fi
		git reset --hard ${check}
	fi

	# git reset ${gconf}
	# git checkout ${gconf}
	append_multiple_before 'repo\s+module2' '@project2\s+=\s+module2$' \
	"${gconf}" 4 'subconf .*$' "\\
repo module2\\
    RW+   = projadm2\\
\\
@project2 = module2\\
"

	append_multiple_after 'RW\s+=\s+projadm2$' '-\s+VREF\/NAME\/\s+=\s+projadm2$' "${gconf}" 3 'RW+\s\+=\s\+gitoliteadm$' \
"\\
	RW                                     = projadm2\\
	RW VREF/NAME/conf/subs/project2     = projadm2\\
	-  VREF/NAME/                          = projadm2"

	mkdir -p conf/subs
	echo "repo @project2
	RW+   = projadm2" > conf/subs/project2.conf
	git add conf/subs/project2.conf

	if [ ${append} -eq 0 ]; then
		git_status_diff_add_commit_log "${gconf}" "Add new repo module2 to project2 group"
	fi

	check_if_pushed "origin" "[Aa]dd new repo module2 to project2 group$" "master"
	if [ "${check}" = "" ]; then
		echo "no commit 'Add new repo module2 to project2 group'">> ${dirp0}/tests/err
		return 1
	fi
}
