#! /bin/sh
cd $HOME/b2d/sshd
. ../.bash_aliases

env=${1}
all=${2}
if [ "${env}" = "all" ] || [ "${env}" = "ALL" ]; then
	all=${env}
	env=""
fi

sshd_cont="sshd.cont"
if [ "${env}" != "" ] && [ "${env}" != "bash" ]; then
	sshd_cont="sshd.${env}.cont"
fi

docker inspect ${sshd_cont} > /dev/null 2>&1 && docker rm ${sshd_cont}
