#! /bin/sh
folder="$( cd "$( dirname "$(readlink -f "$0")" )" && pwd )"
cd ${folder}
. ${folder}/../scripts/.bash_aliases

env=${1}
all=${2}
if [ "${env}" = "all" ] || [ "${env}" = "ALL" ]; then
	all=${env}
	env=""
fi

sshd_cont="sshd.cont"
if [ "${env}" != "" ] && [ "${env}" != "bash" ]; then
	sshd_cont="sshd.${env}.cont"
fi

docker inspect ${sshd_cont} > /dev/null 2>&1 && docker stop ${sshd_cont}
docker inspect ${sshd_cont} > /dev/null 2>&1 && docker rm ${sshd_cont}


if [ "${all}" = "all" ] || [ "${all}" = "ALL" ]; then
	docker volume rm ${mcron_shippingbay_cont}
fi
