#! /bin/sh
. ../.bash_aliases
ec=$(docker inspect -f '{{ .State.Running }}' sshd.cont 2> /dev/null)
if [ "${ec}" = "false" ]; then
	docker rm sshd.cont
fi
docker inspect sshd.cont > /dev/null 2>&1 || d run -d --name sshd.cont ssh
docker inspect sshd.cont > /dev/null 2>&1 || exit 1
