#! /bin/sh
. ./.bash_aliases
env=${1}
all=${2}
if [ "${env}" = "all" ] || [ "${env}" = "ALL" ]; then
	all=${env}
	env=""
fi
cd $HOME/b2d/nginx
k ${env}
cd $HOME/b2d/apache
k ${env}
alll=$(echo $all | tr '[:upper:]' '[:lower:]')
if [ "${alll}" = "all" ]; then
	cd $HOME/b2d/openldap
	k ${env}
	cd $HOME/b2d/gitolite
	k ${env}
	cd $HOME/b2d/gnupg2
	k ${env} all
fi
if [ "${all}" = "ALL" ]; then
	cd $HOME/b2d/gitolite
	k ${env} ALL
fi
cd $HOME/b2d/mcron
k
