#!/bin/sh

display_usage() {
        echo "Run a data container, and make sure it reuses always the *same* volume data."
	echo "This script must be run with the name of a data container to run."
        echo "The name is mandatory (the ID is not accepted)."
        echo "if it already runs or is exited, it checks if the volume needs to be adjusted."
	echo -e "\nUsage:\n$0 data.container.name\n"
}

# if less or more than one argument supplied, display usage
if [[ "$#" != "1" ]]
then
	display_usage
	exit 1
fi

# check whether user had supplied -h or --help . If yes display usage
if [[ "$*" == "--help" ||  "$*" == "-h" ]]
then
	display_usage
	exit 0
fi

echo "Check if container '$1' exists"
