#!/bin/sh

# curl https://raw.githubusercontent.com/VonC/compileEverything/master/openldap/slapdd.tpl -o /home/docker/b2d/openldap/slapdd
folder="$( cd "$( dirname "$(readlink -f "$0")" )" && pwd )"
cd ${folder}
. ${folder}/../scripts/.bash_aliases

name=openldap
db ${name} . || exit 1

if [ "$(docker images -q ${name} 2> /dev/null)" = "" ]; then
  echo "${name}/build: no ${name} image"
  exit 1
fi

ver=$(docker run --rm ${name} -c 'slapd -VV' 2>&1|tail -2|head -1| cut -d '-' -f 4|cut -d '/' -f 1)
echo "ver='${ver}'"

docker tag ${name} kv:5000/b2d/${name}:${ver}
docker push kv:5000/b2d/${name}:${ver}

if [ "$(docker images -q kv:5000/b2d/${name}:${ver} 2> /dev/null)" = "" ]; then
  echo "git/build: no kv:5000/b2d/${name}:${ver} image"
  exit 1
fi
