#! /bin/sh

folder="$( cd "$( dirname "$(readlink -f "$0")" )" && pwd )"
cd ${folder}
. ${folder}/../scripts/.bash_aliases

image="kv:5000/b2d/openldap:2.4.31"

ec=$(docker inspect -f '{{ .State.Running }}' openldap.cont 2> /dev/null)
if [ "${ec}" = "false" ]; then
	docker rm openldap.cont
fi
docker inspect openldap.cont > /dev/null 2>&1 || d run -d --name openldap.cont ${image}
docker inspect openldap.cont > /dev/null 2>&1 || exit 0
i=$(docker exec -u git openldap.cont ./openldap/ini_ldap_db.sh 2>&1)
[ ! -z "${verbose}" ] && echo "${i}"
