#!/bin/sh

run() {
	set -e
	if [ ! -e tests/newusers/gitolite-admin_as_projadm2 ]; then
		git -c http.https://localhost:6443/.sslCAInfo=${dirp0}/apache/crts -c credential.helper=passwd clone -b master https://projadm2@localhost:6443/hgit/gitolite-admin tests/newusers/gitolite-admin_as_projadm2
	fi
	. tests/utils
	pcrt=$(readlink -f ./apache/crts)
	cd tests/newusers/gitolite-admin_as_projadm2
	pwd
	git_config 6443 "${pcrt}" "projadm2"
	git remote -v
	git ls-remote origin
}
