#!/bin/sh

run() {
	set -e
	pcrt=$(readlink -f ./apache/crts)
	if [ ! -e tests/newusers/module2_as_projextusr2 ]; then
		git -c http.https://localhost:8443/.sslCAInfo=${dirp0}/apache/crts -c credential.helper=passwd clone https://projextusr2@localhost:8443/hgit/module2 tests/newusers/module2_as_projextusr2
	fi
	cd tests/newusers/module2_as_projextusr2
	# echo "git config http.https://localhost:6443/.sslCAInfo ${pcrt}"
	git config http.https://localhost:8443/.sslCAInfo "${pcrt}"
	git config credential.helper passwd
	git remote -v
	git ls-remote origin
}
