#!/bin/sh

run() {
	set -e
	if [ ! -e tests/newusers/module2_as_projusr2 ]; then
		git -c http.https://localhost:6443/.sslCAInfo=${dirp0}/apache/crts -c credential.helper=passwd clone https://projusr2@localhost:6443/hgit/module2 tests/newusers/module2_as_projusr2
	fi
	. tests/b/utils
	pcrt=$(readlink -f ./apache/crts)
	cd tests/newusers/module2_as_projusr2
	pwd
	git_config 6443 "${pcrt}" "projusr2"
	# echo "git config http.https://localhost:6443/.sslCAInfo ${pcrt}"
	git remote -v
	git ls-remote origin
}
