#!/bin/sh

run() {
	set -e
	if [ ! -e tests/newusers/gitolite-admin-ext_as_projextdr ]; then
		git -c http.https://localhost:6443/.sslCAInfo=${dirp0}/apache/crts -c credential.helper=passwd clone -b master_ext https://projextrdr@localhost:6443/hgit/gitolite-admin tests/newusers/gitolite-admin-ext_as_projextdr
	fi
	. tests/b/utils
	pcrt=$(readlink -f ./apache/crts)
	cd tests/newusers/gitolite-admin-ext_as_projextdr
	pwd
	git_config 6443 "${pcrt}" "projextrdr"
	git remote -v
	git ls-remote origin
}
