#!/bin/sh

run() {
	set -e
	pcrt=$(readlink -f ./apache/crts)
	if [ ! -e tests/newusers/gitolite-admin-ext_as_projextdr ]; then
		git -c http.https://localhost:6443/.sslCAInfo=${dirp0}/apache/crts -c credential.helper=passwd clone -b master_ext https://projextrdr@localhost:6443/hgit/gitolite-admin tests/newusers/gitolite-admin-ext_as_projextdr
	fi
	cd tests/newusers/gitolite-admin-ext_as_projextdr
	# echo "git config http.https://localhost:6443/.sslCAInfo ${pcrt}"
	git config http.https://localhost:6443/.sslCAInfo "${pcrt}"
	git config credential.helper passwd
	git remote -v
	git ls-remote origin
}
