#!/bin/sh

run() {
	set -e
	pcrt=$(readlink -f ./apache/crts)
	source tests/b/utils
	cd tests/newusers/gitolite-admin-ext_as_projextdr
	git config http.https://localhost:6443/.sslCAInfo "${pcrt}"
	git config credential.helper passwd
	git config core.pager cat
	git config push.default simple
	git config user.name projadm2
	git config user.email projadm@email.com
	git checkout master_ext &2>/dev/null
	pconf="conf/subs/projectext2.conf"
	if [ ! -e "${pconf}" ]; then
		mkdir -p conf/subs
		echo "repo @projectext2
	RW+	= projextadm2
	" > "${pconf}"
		git add "${pconf}"
	fi
	# git reset ${gconf}
	# git checkout ${gconf}
	append_one "RW\s\+=\s\+projextusr2" "${pconf}" "		RW	= projextusr2"

	if [ ${append} -eq 0 ]; then
		git_status_diff_add_commit_log "${pconf}" "Add projextusr2 to projectext2 as projextrdr for projextadm2"
	fi
	echo "dirp0='${dirp0}' vs. pcrt='${pcrt}'"
	check_if_pushed "origin" "[Aa]dd projextusr2 to projectext2.*" "master_ext"
	if [ "${check}" == "" ]; then
		echo "no commit 'Add projusr2 to project2 as projadm2">> ${dirp0}/tests/err
		return 1
	fi
}
