#!/bin/sh

run() {
	set -e
	pcrt=$(readlink -f ./apache/crts)
	if [ ! -e tests/newcommits/module2_as_projusr2 ]; then
		git -c http.https://localhost:6443/.sslCAInfo=${dirp0}/apache/crts -c credential.helper=passwd clone https://projusr2@localhost:6443/hgit/module2 tests/newcommits/module2_as_projusr2
	fi
	. tests/b/utils
	cd tests/newcommits/module2_as_projusr2
	# echo "git config http.https://localhost:6443/.sslCAInfo ${pcrt}"
	git_config 6443 "${pcrt}"
	git ls-remote origin
	git remote -v
	git config user.name projusr2
	git config user.email projusr2@email.com

	if [ ! -e .git/refs/heads/master ]; then
		git commit --allow-empty -m "First commit as projusr2 on master"
	fi
	set +e; check=$(git branch --no-color | grep -e " master_ext$" 2>&1); set -e
	if [ "${check}" = "" ]; then
		git checkout -b master_ext
	else
		git checkout master_ext
	fi
	# git commit --amend --allow-empty --no-edit
	if [ -e .git/refs/remotes/origin/master_ext ]; then
		set +e; check=$(git branch --no-color --contain origin/master_ext | grep -e " master_ext$" 2>&1); set -e
	fi
	if [ "${check}" = "" ]; then
		git push -u -f origin master_ext
	fi

	check=""
	if [ -e .git/refs/remotes/origin/master ]; then
		set +e; check=$(git branch --no-color --contain origin/master | grep -e " master$" 2>&1); set -e
	fi
	if [ "${check}" = "" ]; then
		echo "push master"
		git push -u origin master
	fi

}
