#!/bin/bash

ln -fs "/usr/share/doc/git/contrib/credential/netrc/git-credential-netrc" "${H}/.gnupg/git-credential-netrc"

f="/usr/share/doc/git/contrib/credential/netrc/git-credential-netrc"

sed -i "s;\\\.gpg;\\\.(asc|gpg);g" "${f}"
sed -i "s;gpg --decrypt;gpg2 --batch -q --decrypt;g" "${f}"
t=$(grep ".netrc.asc" "${f}")
if [[ "${t}" == "" ]]; then
	sed -i '/~\/\.netrc.gpg/ a \\t\t\t\t   ~\/\.netrc.asc' "${f}"
fi

t=$(grep "my $entry_without_num_port;" "${f}")
if [[ "${t}" == "" ]]; then
  sed -i '0,/my \$query = shift @_;/s/my \$query = shift @_;/my $query = shift @_;\n    my $entry_without_num_port;/' "${f}"
fi

t=$(grep "Match potential on host" "${f}")
if [[ "${t}" == "" ]]; then
  sed -i 's/unless (\$query->{\$check} eq \$entry->{\$check}) {/if ($check eq "host" \&\& $query->\{$check\} =~ \/(.*?):\\d+\/ \&\& $1 eq $entry->\{$check\}) {\n\t\t\t\t\t$entry_without_num_port = $entry;\n\t\t\t\t\tlog_debug("Match potential on host %s", $query->\{$check\})\n\t\t\t\t\}\n\t\t\t\tunless ($query->\{$check\} eq $entry->\{$check\} || ( $check eq "host" \&\& $entry_without_num_port) ) \{\n\t\t\t\t\t$entry_without_num_port = undef;/' "${f}"
fi
