#! /bin/sh
. ../.bash_aliases
cd $HOME/b2d/nginx

nginx_cont="nginx.cont"

if [ "${1}" != "" ]; then
	nginx_cont="nginx.${1}.cont"
fi

docker inspect ${nginx_cont} > /dev/null 2>&1 && docker kill ${nginx_cont} && docker rm ${nginx_cont}
