#! /bin/sh
cd $HOME/b2d/nginx
. ../.bash_aliases

env=${1}
if [ "${env}" = "all" ] || [ "${env}" = "ALL" ]; then
	env=""
fi

nginx_cont="nginx.cont"
if [ "${env}" != "" ]; then
	nginx_cont="nginx.${env}.cont"
fi

docker inspect ${nginx_cont} > /dev/null 2>&1 && docker kill ${nginx_cont} 2> /dev/null
docker inspect ${nginx_cont} > /dev/null 2>&1 && docker rm ${nginx_cont}
