#! /bin/sh
. ../.bash_aliases
cd $HOME/b2d/apache
./run $1
cd $HOME/b2d/nginx

apache_cont="apache.cont"
nginx_cont="nginx.cont"
envs_cnf="envs.cnf"

if [ "${1}" != "" ]; then
	apache_cont="apache.${1}.cont"
	nginx_cont="nginx.${1}.cont"
	envs_cnf="envs.${1}.cnf"
fi

port_https=$(sed -n "s#^\s*@PORT_NGINX_HTTPS@\s*=\s*##p" ../envs/${envs_cnf})
if [ "${port_https}" == "" ]; then echo "missing @PORT_NGINX_HTTPS@ in '$HOME/b2d/envs/${envs_cnf}'"; exit 0; fi
port_http=$(sed -n "s#^\s*@PORT_NGINX_HTTP@\s*=\s*##p" ../envs/${envs_cnf})
if [ "${port_http}" == "" ]; then echo "missing @PORT_NGINX_HTTP@ in '$HOME/b2d/envs/${envs_cnf}'"; exit 0; fi

docker inspect ${apache_cont} > /dev/null 2>&1 || { echo "${nginx_cont}/run: apache_cont '${apache_cont}' not started"; exit 1; }
docker inspect ${nginx_cont} > /dev/null 2>&1 || docker run -it -d --name ${nginx_cont} -p ${port_http}:80 -p ${port_https}:443 --link ${apache_cont}:nginx.apache.cont nginx
