#!/bin/sh

run() {
	set -e
	if [ ! -e tests/blessed/gitolite-admin-ext ]; then
		git -c http.https://localhost:6443/.sslCAInfo=${dirp0}/apache/crts -c credential.helper=passwd clone https://gitoliteadm@localhost:6443/hgit/gitolite-admin tests/blessed/gitolite-admin-ext
	fi
	source tests/b/utils
	pcrt=$(readlink -f ./apache/crts)
	cd tests/blessed/gitolite-admin-ext
	git_config 6443 "${pcrt}"
	if [ ! -e .git/refs/heads/master_ext ]; then
		fc=$(git log --reverse --pretty=format:%H|head -1)
		git checkout -b master_ext ${fc}
	fi
	if [ ! -e .git/refs/heads/master_ext ]; then
		echo "no master_ext branch found">> tests/err
		return 1
	fi
	git checkout master_ext
	gconf="conf/gitolite.conf"
	git reset ${gconf}
	# git checkout ${gconf}

	append_one "subconf " ${gconf} "
subconf \"subs/*.conf\""
	if [ ${append} -eq 0 ]; then
		git_status_diff_add_commit_log "${gconf}" "Add subs include directive in master_ext"
	fi

	prepend_multiple 'repo\s+@all$' 'RW\+\s+=\s+projextrdr$' "${gconf}" 2 \
"repo @all\\
	RW+		=	projextrdr\\
"
	if [ ${prepend} -eq 0 ]; then
		git_status_diff_add_commit_log "${gconf}" "Add projextrdr to @all in master_ext"
	fi

	check_if_pushed "origin" "[Aa]dd projextrdr to @all in master_ext.*" "master_ext"
	if [ "${check}" = "" ]; then
		echo "no commit 'Add projextrdr to @all in master_ext">> ${drp0}/tests/err
		return 1
	fi
}
