#!/bin/sh

run() {
	set -e
	if [ ! -e tests/blessed/gitolite-admin-ext ]; then
		git -c http.https://localhost:6443/.sslCAInfo=${dirp0}/apache/crts -c credential.helper=passwd clone https://gitoliteadm@localhost:6443/hgit/gitolite-admin tests/blessed/gitolite-admin-ext
	fi
	. tests/b/utils
	pcrt=$(readlink -f ./apache/crts)
	cd tests/blessed/gitolite-admin-ext
	pwd
	git_config 6443 "${pcrt}" "gitoliteadm"
	gconf="conf/gitolite.conf"

	if [ ! -e .git/refs/heads/master_ext ]; then
		fc=$(git log --reverse --pretty=format:%H|head -1)
		git checkout -b master_ext ${fc}
	fi
	if [ ! -e .git/refs/heads/master_ext ]; then
		echo "no master_ext branch found">> tests/err
		return 1
	fi
	git checkout master_ext

	if [ ${reset} -eq 0 ]; then
		echo "resetting to 'gitolite setup'"
		check=$(git log --format=format:%H --grep "gitolite setup.*\.pub$" master)
		if [ "check" = "" ]; then
			echo "Impossible to reset: 'gitolite setup.*\\.pub$'' not found" >> ${dirp0}/tests/err
			return -1
		fi
		git reset --hard ${check}
		reset=1
	fi

	git reset ${gconf}
	# git checkout ${gconf}

	append_one "subconf " ${gconf} "
subconf \"subs/*.conf\""
	if [ ${append} -lt 0 ]; then
		echo "Incorrect number of subconf in '${gconf}'">> ${dirp0}/tests/err
		return -1
	fi
	if [ ${append} -eq 0 ]; then
		git_status_diff_add_commit_log "${gconf}" "Add subs include directive in master_ext"
	fi

	prepend_multiple 'repo\s+@all$' 'RW\+\s+=\s+projextrdr$' "${gconf}" 2 \
"repo @all\\
	RW+		=	projextrdr\\
"
	if [ ${prepend} -lt 0 ]; then
		echo "Incorrect number of repo @all RW+ projextrdr in '${gconf}'">> ${dirp0}/tests/err
		return -1
	fi
	if [ ${prepend} -eq 0 ]; then
		git_status_diff_add_commit_log "${gconf}" "Add projextrdr to @all in master_ext"
	fi

	check_if_pushed "origin" "[Aa]dd projextrdr to @all in master_ext.*" "master_ext"
	if [ "${check}" = "" ]; then
		echo "no commit 'Add projextrdr to @all in master_ext">> ${dirp0}/tests/err
		return 1
	fi
}
