#!/bin/sh

run() {
	set -e
	if [ ! -e tests/blessed/gitolite-admin-ext ]; then
		git -c http.https://localhost:6443/.sslCAInfo=${dirp0}/apache/crts -c credential.helper=passwd clone https://gitoliteadm@localhost:6443/hgit/gitolite-admin tests/blessed/gitolite-admin-ext
	fi
	source tests/b/utils
	pcrt=$(readlink -f ./apache/crts)
	cd tests/blessed/gitolite-admin-ext
	git_config 6443 "${pcrt}"
	if [ ! -e .git/refs/heads/master_ext ]; then
		fc=$(git log --reverse --pretty=format:%H|head -1)
		git checkout -b master_ext ${fc}
	fi
	if [ ! -e .git/refs/heads/master_ext ]; then
		echo "no master_ext branch found">> tests/err
		return 1
	fi
	gconf="conf/gitolite.conf"
	git reset ${gconf}
	# git checkout ${gconf}

	append_one "subconf " ${gconf} "
subconf \"subs/*.conf\""
	if [ ${append} -eq 0 ]; then
		git_status_diff_add_commit_log "${gconf}" "Add subs include directive in master_ext"
	fi

	append_multiple 'repo\s+module2' '@projectext2\s+=\s+module2$' \
	"${gconf}" 4 "
repo module2
    RW+   = projextadm2

@projectext2 = module2"

	append_multiple_after 'RW\s+=\s+projextadm2$' '-\s+VREF\/NAME\/\s+=\s+projextadm2$' "${gconf}" 3 'RW+\s\+=\s\+gitoliteadm$' \
"\\
	RW                                     = projextadm2\\
	RW VREF/NAME/conf/subs/projectext2     = projextadm2\\
	-  VREF/NAME/                          = projextadm2"

    mkdir -p conf/subs
	echo "repo @projectext2
	RW+   = projextadm2
	" > conf/subs/projectext2.conf
	git add conf/subs/projectext2.conf

	if [ ${append} -eq 0 ]; then
		git_status_diff_add_commit_log "${gconf}" "Add new repo module2 to projectext2 group"
	fi

	check_if_pushed "origin" "[Aa]dd new repo module2 to projectext2.*" "master_ext"
	if [ "${check}" == "" ]; then
		echo "no commit 'Add new repo module2 to projectext2">> ${drp0}/tests/err
		return 1
	fi
}
