#!/bin/sh

run() {
	set -e
	cd tests/blessed/gitolite-admin
	git config http.sslCAInfo ../../../apache/crts
	git config core.pager cat
	git checkout master
	git config push.default simple
	git config user.name projextrdr
	git config user.email projextrdr@emaim.com
	gconf="conf/gitolite.conf"
	# http://stackoverflow.com/questions/3717772/regex-grep-for-multi-line-search-needed
	i=$(awk '/repo\s+@all/,/RW\+\s+=\s+projextrdr$/' ${gconf}|wc -l)
	if [ "${i}" -ne 2 ]; then
		# http://stackoverflow.com/questions/9533679/how-to-insert-a-text-at-the-beginning-of-a-file
	   	sed -i '1s/^/repo @all\n	RW+		=	projextrdr\n/' ${gconf}
		echo "
subconf \"subs/*.conf\"" >> ${gconf}
	   	git diff --color
	   	git add ${gconf}
	   	git commit -m "Add projextrdr to @all"
	fi
	check=$(git log --oneline --grep "[Aa]dd projextrdr to @\?all.*" master)
	if [ "${check}" == "" ]; then
		echo "no commit 'Add projextrdr to @all' found">> tests/err
		return 1
	fi
	git fetch origin
	# http://stackoverflow.com/questions/462974/what-are-the-differences-between-double-dot-and-triple-dot-in-git-com
	check=$(git log --oneline --grep "[Aa]dd projextrdr to @\?all.*" origin/master)
	if [ "${check}" == "" ]; then
		git push -u origin master
	fi
	git fetch origin
	check=$(git log --oneline --grep "[Aa]dd projextrdr to @\?all.*" origin/master)
	if [ "${check}" == "" ]; then
		echo "no commit 'Add projextrdr to @all' found on origin/master">> tests/err
		return 1
	fi
}
