#!/bin/sh

run() {
	set -e
	if [ ! -e tests/blessed/module2_as_projextadm2 ]; then
		git -c http.https://localhost:6443/.sslCAInfo=${dirp0}/apache/crts -c credential.helper=passwd clone https://projextadm2@localhost:6443/hgit/module2 tests/blessed/module2_as_projextadm2
	fi
	. tests/utils
	pcrt=$(readlink -f ./apache/crts)
	cd tests/blessed/module2_as_projextadm2
	pwd
	git_config 6443 "${pcrt}" "projextadm2"
	git remote -v
	git ls-remote origin
}
