#!/bin/sh

run() {
	set -e
	cd tests/blessed/gitolite-admin
	git config http.sslCAInfo ../../../apache/crts
	git config core.pager cat
	git config push.default simple
	git config user.name projextrdr
	git config user.email projextrdr@emaim.com
	git checkout master
	gconf="conf/gitolite.conf"
	# git reset ${gconf}
	# git checkout ${gconf}
	# http://stackoverflow.com/questions/3717772/regex-grep-for-multi-line-search-needed
	i=$(awk '/repo\s+module2/,/@project2\s+=\s+module2$/' ${gconf}|wc -l)
	if [ "${i}" -ne 4 ]; then
		# http://stackoverflow.com/questions/9533679/how-to-insert-a-text-at-the-beginning-of-a-file
		echo "
subconf \"subs/*.conf\"

repo module2
    RW+   = projadm2

@project2 = module2" >> ${gconf}
		# http://stackoverflow.com/questions/15559359/insert-line-after-first-match-using-sed
		sed -i '/    RW+     =   gitoliteadm/a\
    RW                                     = projadm2\
    RW VREF/NAME/conf/subs/project2        = projadm2\
    -  VREF/NAME/                          = projadm2' ${gconf}
    	mkdir -p conf/subs
	   	echo "repo @project2
        RW+   = projadm2
" > conf/subs/project2.conf
	   	git diff --color
	   	git status
	   	git add ${gconf}
	   	git add conf/subs/project2.conf
	   	git commit -m "Add new repo module2"
	   	git log --oneline --decorate -3
	fi
}
