#!/bin/sh

run() {
	set -e
	cd tests/blessed/gitolite-admin
	git config http.sslCAInfo ../../../apache/crts
	git config credential.helper passwd
	git config core.pager cat
	git config push.default simple
	git config user.name projextrdr
	git config user.email projextrdr@email.com
	git checkout master
	gconf="conf/gitolite.conf"
	# git reset ${gconf}
	# git checkout ${gconf}
	# http://stackoverflow.com/questions/3717772/regex-grep-for-multi-line-search-needed
	i=$(awk '/repo\s+module2/,/@project2\s+=\s+module2$/' ${gconf}|wc -l)
	if [ "${i}" -ne 4 ]; then
		# http://stackoverflow.com/questions/9533679/how-to-insert-a-text-at-the-beginning-of-a-file
		echo "
subconf \"subs/*.conf\"

repo module2
    RW+   = projadm2

@project2 = module2" >> ${gconf}
		# http://stackoverflow.com/questions/15559359/insert-line-after-first-match-using-sed
		sed -i '/    RW+     =   gitoliteadm/a\
    RW                                     = projadm2\
    RW VREF/NAME/conf/subs/project2        = projadm2\
    -  VREF/NAME/                          = projadm2' ${gconf}
    	mkdir -p conf/subs
	   	echo "repo @project2
        RW+   = projadm2
" > conf/subs/project2.conf
	   	git diff --color
	   	git status
	   	git add ${gconf}
	   	git add conf/subs/project2.conf
	   	git commit -m "Add new repo module2"
	   	git log --oneline --decorate -3
	fi
	git fetch origin
	# http://stackoverflow.com/questions/462974/what-are-the-differences-between-double-dot-and-triple-dot-in-git-com
	check=$(git log --oneline --grep "[Aa]dd new repo module2.*" origin/master)
	if [ "${check}" == "" ]; then
		git push -u origin master
	fi
	git fetch origin
	check=$(git log --oneline --grep "[Aa]dd new repo module2.*" origin/master)
	if [ "${check}" == "" ]; then
		echo "no commit 'Add new repo module2">> tests/err
		return 1
	fi
}
