#!/bin/sh

run() {
	set -e
	if [ ! -e tests/blessed/gitolite-admin ]; then
		git -c http.https://localhost:6443/.sslCAInfo=${dirp0}/apache/crts -c credential.helper=passwd clone https://gitoliteadm@localhost:6443/hgit/gitolite-admin tests/blessed/gitolite-admin
	fi
	. tests/b/utils
	pcrt=$(readlink -f ./apache/crts)
	cd tests/blessed/gitolite-admin
	pwd
	git_config 6443 "${pcrt}" "projextrdr"
	gconf="conf/gitolite.conf"

	if [ ${reset} -eq 0 ]; then
		echo "resetting to 'gitolite setup'"
		check=$(git log --format=format:%H --grep "gitolite setup.*\.pub$" master)
		if [ "check" = "" ]; then
			echo "Impossible to reset: gitolite setup.*\\.pub$ not found" >> ${dirp0}/tests/err
			return -1
		fi
		git reset --hard ${check}
		reset=1
	fi
	git reset ${gconf}
	# git checkout ${gconf}

	append_one "subconf " ${gconf} "
subconf \"subs/*.conf\""
	if [ ${append} -eq 0 ]; then
		git_status_diff_add_commit_log "${gconf}" "Add subs include directive in master"
	fi
	if [ ${append} -lt 0 ]; then
		echo "Incorrect number of subconf in '${gconf}'">> ${dirp0}/tests/err
		return -1
	fi

	prepend_multiple 'repo\s+@all$' 'RW\+\s+=\s+projextrdr$' "${gconf}" 2 \
"repo @all\\
	RW+		=	projextrdr\\
"
	if [ ${prepend} -lt 0 ]; then
		echo "Incorrect number of repo @all RW+ projextrdr in '${gconf}'">> ${dirp0}/tests/err
		return -1
	fi
	if [ ${prepend} -eq 0 ]; then
		git_status_diff_add_commit_log "${gconf}" "Add projextrdr to @all in master"
	fi

	check_if_pushed "origin" "[Aa]dd projextrdr to @all in master$" "master"
	if [ "${check}" = "" ]; then
		echo "no commit 'Add projextrdr to @all in master">> ${dirp0}/tests/err
		return 1
	fi
}
