#!/bin/sh

git_config() {
	git config http.https://localhost:6443/.sslCAInfo ${dirp0}/apache/crts
	git config credential.helper passwd
	git config core.pager cat
	git config push.default simple
	git config user.name projextrdr
	git config user.email projextrdr@email.com
	git config color.ui always
}

append_one() {
	s="${1}"
	f="${2}"
	a="${3}"
	c="${4}"
	set +e
	i=$(grep "${s}" ${f}|wc -l)
	set -e
	if [ "${i}" -ne 1 ]; then
		echo "${a}" >> ${f}
		git status
		git diff --color
		git add ${f}
		git commit -m "${4}"
		git log --oneline --decorate -3
	fi
}
