#!/bin/sh

git_config() {
	git config http.https://localhost:6443/.sslCAInfo ${dirp0}/apache/crts
	git config credential.helper passwd
	git config core.pager cat
	git config push.default simple
	git config user.name projextrdr
	git config user.email projextrdr@email.com
	git config color.ui always
}
