#! /bin/sh
# http://stackoverflow.com/questions/15541876/script-path-bash-source0-bad-substitution
kv=$(readlink -f "$0")
kv=$( dirname "${kv}" )
b2d="$( cd -P "$( dirname "$SOURCE" )/../.." && pwd )"

. ${b2d}/scripts/.bash_aliases

consulver=0.6.4
if [[ "$(docker images -q hashicorp/consul:${consulver} 2> /dev/null)" == "" ]]; then
	db hashicorp/consul:${consulver} ${kv}/docker-consul/0.6
fi

if [[ "$(docker inspect -f {{.State.Running}} consul 2> /dev/null)" == "" ]]; then
	# docker run -d -p 8400:8400 -p 8500:8500 -p 8600:53/udp -h consul --name consul --restart always hashicorp/consul:${consulver} -bootstrap -ui-dir /ui -client 0.0.0.0
	docker run -d --net=host -p 8400:8400 -p 8500:8500 -p 53:8600/tcp -p 53:8600/udp -h consul --name consul --restart always hashicorp/consul:${consulver} server -bind=192.168.99.100 -client=0.0.0.0 -bootstrap -ui
	docker logs -f consul&
	# curl http://localhost:8500/v1/health/service/consul?pretty
	# curl -L http://localhost:8500/ui
fi
if [[ "$(docker inspect -f {{.State.Running}} consul 2> /dev/null)" != "true" ]]; then
	echo hashicorp/consul:${consulver} is not running
	exit 1
fi

./gen_ssl_key_and_crt.sh
if [[ "$(docker inspect -f {{.State.Running}} registry 2> /dev/null)" == "" ]]; then
	docker run -d -p 5000:5000 --restart=always --name registry \
		-v $(pwd)/certs:/certs \
		-e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/crt \
		-e REGISTRY_HTTP_TLS_KEY=/certs/key \
		registry:2
fi
if [[ ! -e /var/lib/boot2docker/registry.crt ]]; then
	sudo cp ${kv}/certs/crt /var/lib/boot2docker/registry.crt
fi
if [[ "$(grep registry.crt /var/lib/boot2docker/bootsync.sh)" == "" ]]; then
	sudo sh -c 'echo cat /var/lib/boot2docker/registry.crt \| sudo tee -a /etc/ssl/certs/ca-certificates.crt | sudo tee -a /var/lib/boot2docker/bootsync.sh >/dev/null'
fi
rline=$(tail -2 /var/lib/boot2docker/registry.crt | head -1)
if [[ "$(grep ${rline} /etc/ssl/certs/ca-certificates.crt)" == "" ]]; then
	cat /var/lib/boot2docker/registry.crt | sudo tee -a /etc/ssl/certs/ca-certificates.crt
fi
grep $rline /etc/ssl/certs/ca-certificates.crt|wc

# openssl s_client -connect 192.168.99.100:5000 -showcerts </dev/null 2>/dev/null | openssl x509 -outform PEM | sudo tee -a /etc/ssl/certs/ca-certificates.crt
# docker@kv:~$ openssl s_client -connect 192.168.99.100:5000 -showcerts </dev/null 2>/dev/null | openssl x509 -outform PEM | sudo tee -a /etc/ssl/certs/ca-certificates.crt

# docker@kv:/mnt/sda1/var/lib/boot2docker$ curl https://localhost:5000/v2/
# curl: (60) SSL certificate problem: self signed certificate
# docker@kv:/mnt/sda1/var/lib/boot2docker$ sudo cat /var/lib/boot2docker/server.pem  | sudo tee -a /etc/ssl/certs/ca-certificates.crt

# openssl s_client -connect 192.168.99.100:5000 -showcerts </dev/null 2>/dev/null | openssl x509 -outform PEM | sudo tee -a /etc/ssl/certs/ca-certificates.crt
# rline=$(tail -2 /var/lib/boot2docker/registry.crt | head -1)
# grep $rline /etc/ssl/certs/ca-certificates.crt|wc
