#! /bin/sh

if [ "$(docker images -q gitolite.repos 2> /dev/null)" = "" ]; then
  docker build -t gitolite.repos -f $HOME/b2d/gitolite/Dockerfile.repos $HOME/b2d/gitolite || exit 1
fi
docker inspect gitolite.repos.cont > /dev/null 2>&1 || docker create --name="gitolite.repos.cont" gitolite.repos
grpath=$(docker inspect -f '{{ index .Volumes "/home/git/repositories" }}' gitolite.repos.cont)
if [ ! -f grepos ]; then
	echo "grepos: new container"
	echo ${grpath}>grepos
else
	echo "grepos: existing container"
	fgrpath=$(cat grepos)
	if [ "${grpath}" == "${fgrpath}" ]; then
		echo "grepos: same path"
	else
		echo "grepos: different paths"
		echo "(file '${fgrpath}') vs."
		echo "(cont '${grpath}')"
		rm -Rf ${grpath}
		mv ${fgrpath} ${grpath}
		echo ${grpath}>grepos
	fi
fi

if [ "$(docker images -q gitolite 2> /dev/null)" = "" ]; then
  docker build -t gitolite $HOME/b2d/gitolite || exit 1
fi
docker inspect gitolite.cont > /dev/null 2>&1 || docker create --name="gitolite.cont" gitolite
