#! /bin/sh

docker inspect gitolite > /dev/null 2>&1 || docker build -t gitolite $HOME/b2d/gitolite || exit $?
docker inspect gitolite.repos > /dev/null 2>&1 || docker build -t gitolite.repos -f $HOME/b2d/gitolite/Dockerfile.repos $HOME/b2d/gitolite
