FROM git:latest

MAINTAINER VonC <vonc@laposte.net>

# ENV http_proxy http://<user>:<pwd>@proxy.company:80
# ENV https_proxy http://<user>:<pwd>@proxy.company:80
# ENV no_proxy .company,.sock,localhost,127.0.0.1,::1,192.168.59.103

RUN mkdir /home/git/repositories ; chown -R git:git /home/git/repositories

VOLUME ["/home/git/repositories"]

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["echo Data Volume Container for gitolite repos"]
