FROM git:latest

MAINTAINER VonC <vonc@laposte.net>

# ENV http_proxy http://<user>:<pwd>@proxy.company:80
# ENV https_proxy http://<user>:<pwd>@proxy.company:80
# ENV no_proxy .company,.sock,localhost,127.0.0.1,::1,192.168.59.103

WORKDIR /home/git
RUN mkdir -p shippingbay_git/incoming && \
	mkdir -p shippingbay_git/outgoing && \
	chown -R git:git /home/git

VOLUME ["/home/git/shippingbay_git"]

ENTRYPOINT ["/bin/sh", "-c"]
CMD ["echo Data Volume Container for shippingbay_git"]
