#! /bin/sh
. ../.bash_aliases

if [ "${1}" = "bash" ]; then
	docker inspect mcron.shippingbay.test.cont > /dev/null 2>&1 || docker create --name="mcron.shippingbay.test.cont" mcron.shippingbay /bin/true
	docker create -it --name mcron.test.cont --volumes-from mcron.shippingbay.test.cont mcron bash
	docker cp "$HOME/b2d/envs/.envs.example.private" mcron.test.cont:/home/git/.envs.private
	docker cp "$HOME/b2d/mcron/clean_shipping_bay.guile" mcron.test.cont:/home/git/.config/cron/
	docker cp "$HOME/b2d/mcron/pull_external.guile" mcron.test.cont:/home/git/.config/cron/
	docker start -a -i mcron.test.cont
	docker inspect mcron.test.cont > /dev/null 2>&1 && docker rm mcron.test.cont
	docker inspect mcron.shippingbay.test.cont > /dev/null 2>&1 && docker rm mcron.shippingbay.test.cont
	exit 0
fi

mcron_cont="mcron.cont"
mcron_shippingbay_cont="mcron.shippingbay.cont"
mshippingbay="mshippingbay"

if [ "${1}" != "" ]; then
	mcron_cont="gitolite.${1}.cont"
	mcron_shippingbay_cont="mcron.shippingbay.${1}.cont"
	mshippingbay="mshippingbay.${1}"
fi
if [ "${1}" != "external" ]; then
	mcron_shippingbay_cont=""
	mshippingbay=""
fi

if [ "${mshippingbay}" != "" ]; then
	docker inspect ${mcron_shippingbay_cont} > /dev/null 2>&1 || docker create --name="${mcron_shippingbay_cont}" mcron.shippingbay /bin/true

	. ../updateDataContainerPath
	updatePath ${mcron_shippingbay_cont} "$HOME/b2d/mcron" ${mshippingbay}
	docker inspect ${mcron_cont} > /dev/null 2>&1 || docker run --name="${mcron_cont}" --volumes-from ${mcron_shippingbay_cont} mcron
else
	docker inspect ${mcron_cont} > /dev/null 2>&1 || docker run --name="${mcron_cont}" mcron
fi
