#! /bin/sh
. ../.bash_aliases
ec=$(docker inspect -f '{{ .State.Running }}' mcron.cont 2> /dev/null)
if [ "${ec}" = "false" ]; then
	docker rm mcron.cont
fi
docker inspect mcron.cont > /dev/null 2>&1 || d run -d --name mcron.cont mcron
docker inspect mcron.cont > /dev/null 2>&1 || exit 1
