#! /bin/sh
. ../.bash_aliases

if [ "${1}" = "bash" ]; then
	docker inspect mcron.shippingbay.test.cont > /dev/null 2>&1 || docker create --name="mcron.shippingbay.test.cont" mcron.shippingbay /bin/true
	docker run -it --rm  --name mcron.test --volumes-from mcron.shippingbay.test.cont mcron bash
	docker inspect mcron.shippingbay.test.cont > /dev/null 2>&1 && docker rm mcron.shippingbay.test.cont
	exit 0
fi

