#!/bin/bash
chmod 644 /home/git/.ssh/root.pub
chmod 600 /home/git/.ssh/root
chown git:git /home/git/.ssh/root*
k=$(ssh-keyscan -t ecdsa -p 2200 mcron.sshd.cont 2>&1 | grep ecdsa | grep nist)
if [[ "${k}" != "" ]]; then
	key="${k#* }"
	k="[mcron.sshd.cont]:2200 ${key}"
	echo "${k}" > /home/git/.ssh/known_hosts
	ip=$(grep mcron.sshd.cont /etc/hosts|awk '{print $1;}')
	k="[${ip}]:2200 ${key}"
	echo "${k}" >> /home/git/.ssh/known_hosts
	chmod 644 /home/git/.ssh/known_hosts
	chown git:git /home/git/.ssh/known_hosts
fi
