#!/bin/bash
chmod 644 /home/git/.ssh/root.pub
chmod 600 /home/git/.ssh/root
chown git:git /home/git/.ssh/root*
# check if ssh-keyscan -H wouldn't give the right format directly
k=$(ssh-keyscan -t ecdsa -p 2200 mcron.sshd.cont 2>&1 | grep ecdsa | grep nist)
if [[ "${k}" != "" ]]; then
	key="${k#* }"
	k="[mcron.sshd.cont]:2200 ${key}"
	echo "${k}" > /home/git/.ssh/known_hosts
	ip=$(grep mcron.sshd.cont /etc/hosts|awk '{print $1;}')
	k="[${ip}]:2200 ${key}"
	echo "${k}" >> /home/git/.ssh/known_hosts
	chmod 644 /home/git/.ssh/known_hosts
	chown git:git /home/git/.ssh/known_hosts
fi
export no_proxy=.cont,${no_proxy}
cd /home/git/.ssh
a=$(grep "apache.external.crt" curl-ca-bundle.crt)
if [ "${a}" == "" ]; then
	echo "">> curl-ca-bundle.crt
	cat crts>> curl-ca-bundle.crt
fi
git config --file /home/git/.gitconfig http.sslCAInfo /home/git/.ssh/curl-ca-bundle.crt
