#! /bin/sh

folder="$( cd "$( dirname "$(readlink -f "$0")" )" && pwd )"
cd ${folder}
. ${folder}/../scripts/.bash_aliases

name=apache

if [ "$(docker images -q ${name}.deb 2> /dev/null)" == "" ]; then
	db ${name}.deb . Dockerfile.build || exit 1
fi
if [ "$(docker images -q apache.inst 2> /dev/null)" = "" ]; then
	docker inspect apache.deb.cont > /dev/null 2>&1 || docker run -d -t --name=apache.deb.cont apache.deb
	docker inspect apache.inst.cont > /dev/null 2>&1 || docker run -u root -it --name=apache.inst.cont --volumes-from apache.deb.cont --entrypoint "/bin/sh" openldap -c "dpkg -i /root/deb/apache2-4_2.4.10-1_amd64.deb"
	docker commit apache.inst.cont apache.inst
	docker rm apache.deb.cont apache.inst.cont
fi
db ${name} . || exit 1

ver=$(docker run --rm ${name} -c "apachectl -v"|head -1|cut -d '/' -f 2|awk '{print $1}')
echo "ver='${ver}'"

docker tag ${name} kv:5000/b2d/${name}:${ver}
docker push kv:5000/b2d/${name}:${ver}

if [ "$(docker images -q kv:5000/b2d/${name}:${ver} 2> /dev/null)" = "" ]; then
  echo "git/build: no kv:5000/b2d/${name}:${ver} image"
  exit 1
fi

./getcrt
