#! /bin/bash

docker build -t apache.deb -f $HOME/b2d/apache/Dockerfile.build $HOME/b2d/apache
docker inspect apache.deb > /dev/null || docker run -d -t --name=apache.deb apache.deb
docker inspect apache.inst > /dev/null 2>&1 || docker run -it --name=apache.inst --volumes-from apache.deb git dpkg -i /root/deb/apache2-4_2.4.10-1_amd64.deb
if [[ "$(docker images -q apache.inst 2> /dev/null)" == "" ]]; then
  docker commit apache.inst apache.inst
fi
docker build -t apache $HOME/b2d/apache
