#! /bin/sh
. ../.bash_aliases
cd $HOME/b2d/apache

env=${1}
if [[ "${env}" == "all" || "${env}" == "ALL" ]]; then
	env=""
fi

apache_cont="apache.cont"
if [ "${env}" != "" ]; then
	apache_cont="apache.${env}.cont"
fi

docker inspect  ${apache_cont} > /dev/null 2>&1 && docker kill ${apache_cont} 2> /dev/null
docker inspect  ${apache_cont} > /dev/null 2>&1 && docker rm ${apache_cont}

if [ "${env}" = "bash" ]; then
	cd $HOME/b2d/openldap
	kba
	cd $HOME/b2d/gitolite
	kba all
	cd $HOME/b2d/gnupg2
	kba all
fi
